### ISSUE TITLE
Struggling getting latest PHP-FPM containers functioning.

### ISSUE THREAD

**Issue by rquadling** [bitnami/bitnami-docker-php-fpm#100]
Started playing with Bitnami's containers for a development stack. Have mailhog, memcached, mysql, and nginx all doing their thing. I've got my data in mysql with the data held on my local host. I've got backups working of the persistence layer (basically my Makefile contains commands to clone the 'persistence' directory).

Trying to add in php-fpm and I've hit a brick wall trying to get the conf file into the container.

The other containers have a couple of volumes in the docker-compose.yml file of:
```yml
    volumes:
      # Define the persistence layer for Bitnami's persistence container.
      - ./persistence:/bitnami

      # Mount the logs.
      - ./logs/mysql:/opt/bitnami/mysql/logs # nginx for nginx obviously
```
which works fine for nginx and mysql.

But no persistence layer for php. Logs is OK, but not persistence.

The instructions in https://github.com/bitnami/bitnami-docker-php-fpm#configuration just don't seem to match the behaviour of this and other containers.

I need to be able to do a couple of things:

1. Configure PHP-FPM (via an phpfpm.conf)
2. Setup appropriate PHP ini files. When I've ran `docker exec php php-fpm -i | grep ini`, It seems that PHP has been compiled with no support for a location of additional ini files.
```
Configuration File (php.ini) Path => /opt/bitnami/php/lib
Loaded Configuration File => /opt/bitnami/php/lib/php.ini
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
```
3. Adding additional extensions with the ability to rebuild when needed (we've only just started looking at this, so a pointer to the current/best documentation on this would be useful). And how to keep these uptodate when changes to to the Bitnami's PHP-FPM container takes place too.

For some of the simpler vhosts, I've got a working setup (i.e. content served, data saved, reports generated, etc.), but those that have specific PHP settings, we're not seeing how to do that as the instructions are incorrect.

**Comment by juan131** [comment]
Hello @rquadling 

It seems you're right. I run:

```
docker run --name phpfpm -v /path/to/php-fpm:/bitnami bitnami/php-fpm
```

And there's nothing at `/bitnami/php-fpm/` to be persisted. We should be persisting the php and php-fpm configuration files. 

@tompizmor is that normal?

**Comment by tompizmor** [comment]
@rquadling The php-fpm container is a bit different to the other ones that you have checked (nginx or mysql). 
There are two variants of the image, development and production, and it is though to build minimal docker images for php applications as explained in the [example](https://github.com/bitnami/bitnami-docker-php-fpm/tree/master/example). 
Because it is minimal, it does not include `nami` (which is the tool used to initialize and configure the application) and so does not support persistence out-of-the-box.

Regarding the requirements that you pointed out:

> 1. Configure PHP-FPM (via an phpfpm.conf)

It is possible to configure php-fpm by mounting a config file.

> 2. Setup appropriate PHP ini files. When I've ran docker exec php php-fpm -i | grep ini, It seems that PHP has been compiled with no support for a location of additional ini files.

You should also be able to mount a custom `php.ini` file.

> 3. Adding additional extensions with the ability to rebuild when needed (we've only just started looking at this, so a pointer to the current/best documentation on this would be useful). And how to keep these uptodate when changes to the Bitnami's PHP-FPM container takes place too.

I don't think that right now it is possible to recompile php inside the docker image to add extensions.

In any case, you are right that the documentation is not correct so we will update it.

**Comment by rquadling** [comment]
I'm happy with mounting files in, but without documentation as to where, it takes a lot of fiddling and guessing.

The example you've provided doesn't deal with extensions, only the base images + application code. Not actual extensions.

Do I need to fork php-fpm, add my extensions and then build my own containers? Will that produce minimal containers (i.e. without the build tools and whatever junk building leaves behind)?

**Comment by tompizmor** [comment]
You can create your own docker image from bitnami/php-fpm, adding the extensions that you are interested in. 

Alternatively, you can simply start a PHP-FPM container, compile the extensions manually and then commit the docker image to preserve the changes. 

> I suppose a simple example of how to add a PHP extension to php-fpm is what I'm after (timezonedb, xdebug, wddx, php_pdo_dblib)

Document how to add an extension looks like a good idea to me. I will create a task to make sure we add it to the README. In the meantime, I've successfully added the xdebug extension following these instructions:

1. Install requirements:

```
$ install_packages git autoconf build-essential
```

2. Get module source code

```
$ wget https://github.com/xdebug/xdebug/archive/2.6.0.tar.gz
$ tar xzf 2.6.0.tar.gz
$ cd xdebug-2.6.0
```

3. Configure, build and install:

```
$ phpinze
./configure --enable-xdebug
make
make install
```

4. Enable the xdebug extension by adding `zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"` to the */opt/bitnami/php/etc/php.ini* file.

Check that the extension is enabled with `php -m | grep debug`

I guess other modules/extensions will follow a similar approach.

**Comment by rquadling** [comment]
This won't make minimal images. All the build tools will be left in play. From a running container's perspective, all I'm trying to achieve is an additional .so file and any necessary or supporting files. No need for the source code, build artefacts, build system, etc.

Ideally the method used to make the current minimal PHP-FPM with an appropriate mechanism to include additional extensions (mainly PECL source but also xDebug) would be a real winner.

**Comment by tompizmor** [comment]
@rquadling You're right. The images won't be minimal. I thought that at development stage you didn't care about the image size.

In order to build a minimal image with xdebug extension, you can use a multistage Dockerfile like the following:

```
FROM bitnami/php-fpm:7.1 as builder
RUN install_packages git autoconf build-essential
WORKDIR /app
RUN wget https://github.com/xdebug/xdebug/archive/2.6.0.tar.gz && \
    tar xzf 2.6.0.tar.gz && \
    cd xdebug-2.6.0 && \
    phpize && \
    ./configure --enable-xdebug && \
    make && make install


FROM bitnami/php-fpm:7.1
COPY --from=builder /opt/bitnami/php/lib/php/extensions/xdebug.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"' >> /opt/bitnami/php/etc/php.ini
```

The resultant docker image is just like ` bitnami/php-fpm:7.1` with the additional .so for the xdebug extension.

**Comment by rquadling** [comment]
So. Strange thing. I have built a minimal container that I can connect to from the command line and run `php -m` or `php-fpm -m` and see the additional extensions I've incorporated.

If I run `php --ini` in the container, I can see the INI file that is being used.

If I run `cat` against the ini file, I can see the correct extension entries at the end of the ini file
```ini
zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"
extension=igbinary.so
extension=msgpack.so
extension=pdo_dblib.so
extension=timezonedb.so
extension=redis.so
extension=memcached.so
```

If I run one of the command line utils we use that would require any of the new extensions, all is good.

Loading a controller that shows `phpinfo()` via a browser, I see the same INI filename as I do via the command line, I see my additional environment variables injected by my docker compose yaml file. But I don't see the extensions.

Adding a `print_r(get_loaded_extensions());` to the controller that outputs the phpinfo and I don't see the additional extensions.

```php
            phpinfo();
            // Quick dump of data regarding extensions and php.ini config
            $ext = get_loaded_extensions();
            $zext = get_loaded_extensions(true);
            $scanned = php_ini_scanned_files();
            $loaded = php_ini_loaded_file();
            $config = file_get_contents('/opt/bitnami/php/lib/php.ini');
            sort($ext);
            sort($zext);
            echo
                '<pre>',
                print_r($ext, true), PHP_EOL,
                print_r($zext, true), PHP_EOL,
                'Scanned:', $scanned, PHP_EOL,
                'Loaded:', $loaded, PHP_EOL,
                'INI:', $config, PHP_EOL,
                '</pre>';
```

This outputs (at the end of the phpinfo() output ...

```
Array
(
    [0] => Core
    [1] => PDO
    [2] => Phar
    [3] => Reflection
    [4] => SPL
    [5] => SimpleXML
    [6] => bcmath
    [7] => bz2
    [8] => calendar
    [9] => cgi-fcgi
    [10] => ctype
    [11] => curl
    [12] => date
    [13] => dom
    [14] => exif
    [15] => fileinfo
    [16] => filter
    [17] => ftp
    [18] => gd
    [19] => gettext
    [20] => gmp
    [21] => hash
    [22] => iconv
    [23] => intl
    [24] => json
    [25] => ldap
    [26] => libxml
    [27] => mbstring
    [28] => mcrypt
    [29] => mysqli
    [30] => mysqlnd
    [31] => openssl
    [32] => pcntl
    [33] => pcre
    [34] => pdo_mysql
    [35] => pdo_sqlite
    [36] => posix
    [37] => readline
    [38] => session
    [39] => soap
    [40] => sockets
    [41] => sqlite3
    [42] => standard
    [43] => tidy
    [44] => tokenizer
    [45] => xml
    [46] => xmlreader
    [47] => xmlrpc
    [48] => xmlwriter
    [49] => xsl
    [50] => zip
    [51] => zlib
)

Array
(
)

Scanned:
Loaded:
INI:[PHP]

;;;;;;;;;;;;;;;;;;;
; About php.ini   ;
;;;;;;;;;;;;;;;;;;;
; PHP's initialization file, generally called php.ini, is responsible for
; configuring many of the aspects of PHP's behavior.
... [SNIPPED] ...

; Local Variables:
; tab-width: 4
; End:
upload_max_filesize = 40M
post_max_size = 40M
extension_dir = /opt/bitnami/php/lib/php/extensions
date.timezone = UTC
zend_extension = opcache.so
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 60
opcache.fast_shutdown = 1
zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"
extension=igbinary.so
extension=msgpack.so
extension=pdo_dblib.so
extension=timezonedb.so
extension=redis.so
extension=memcached.so
```

So. Everything is in the right place, but it seems PHP-FPM is running from an old php.ini file.

I suspect the reason for this is that the Bitnami containers have:
```
WORKDIR /app
CMD ["php-fpm","-F","--pid","/opt/bitnami/php/tmp/php-fpm.pid","-c","/opt/bitnami/php/conf/php-fpm.conf"]
```

This is running the pool not as a service, but as a command that is loaded there and then. In the vain hope that only 1 CMD is allowed (and that it is the last in the chain so to speak), I tried adding the `CMD` to end of my Dockerfile, but no different result.

This is my Dockerfile:

```
ARG PHP_VERSION
FROM bitnami/php-fpm:$PHP_VERSION as builder
ARG XDEBUG_VERSION
RUN install_packages git autoconf build-essential pkg-config
RUN install_packages libmemcached-dev libmemcached11 libmemcachedutil2 libhashkit2
WORKDIR /app
RUN \
    wget -v --show-progress https://xdebug.org/files/xdebug-$XDEBUG_VERSION.tgz -O xdebug.tgz && \
    tar xzf xdebug.tgz && \
    rm -f xdebug.tgz && \
    cd xdebug-*/ && \
    phpize && \
    ./configure --with-php-config=/opt/bitnami/php/bin/php-config && \
    make && \
    TEST_PHP_ARGS='-n' make test && \
    make install && \
    cd .. && \
    rm -Rf xdebug-*/
RUN \
    pecl install \
        igbinary \
        msgpack \
        pdo_dblib \
        timezonedb \
        redis \
        memcached

ARG PHP_VERSION
FROM bitnami/php-fpm:$PHP_VERSION

# Copy xdebug extensions
COPY --from=builder /opt/bitnami/php/lib/php/extensions/xdebug.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"' >> /opt/bitnami/php/etc/php.ini

# Copy igbinary extension
COPY --from=builder /opt/bitnami/php/lib/php/extensions/igbinary.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'extension=igbinary.so' >> /opt/bitnami/php/etc/php.ini

# Copy msgpack extension
COPY --from=builder /opt/bitnami/php/lib/php/extensions/msgpack.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'extension=msgpack.so' >> /opt/bitnami/php/etc/php.ini

# Copy pdo_pdlib extension
COPY --from=builder /opt/bitnami/php/lib/php/extensions/pdo_dblib.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'extension=pdo_dblib.so' >> /opt/bitnami/php/etc/php.ini

# Copy timezonedb extension
COPY --from=builder /opt/bitnami/php/lib/php/extensions/timezonedb.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'extension=timezonedb.so' >> /opt/bitnami/php/etc/php.ini

# Copy redis extension
COPY --from=builder /opt/bitnami/php/lib/php/extensions/redis.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'extension=redis.so' >> /opt/bitnami/php/etc/php.ini

# Copy memcached extension
COPY --from=builder /opt/bitnami/php/lib/php/extensions/memcached.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'extension=memcached.so' >> /opt/bitnami/php/etc/php.ini
COPY --from=builder /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0.0 /usr/lib/x86_64-linux-gnu/
RUN ln -sf /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0.0 /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0
RUN ln -sf /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0.0 /usr/lib/x86_64-linux-gnu/libmemcached.so.11
RUN ln -sf /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0.0 /usr/lib/x86_64-linux-gnu/libmemcached.so
COPY --from=builder /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0.0 /usr/lib/x86_64-linux-gnu/
RUN ln -sf /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0.0 /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0
RUN ln -sf /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0.0 /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2
RUN ln -sf /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0.0 /usr/lib/x86_64-linux-gnu/libmemcachedutil.so
```

and this is the Makefile I have

```
build-rquadling-php-fpm-full:
	$(MAKE) build-rquadling-php-fpm EXTRA_PARAMS='--force-rm --no-cache --compress'

build-rquadling-php-fpm:
	$(MAKE) build-rquadling-php-fpm-image PHP_VERSION=7.0 XDEBUG_VERSION=2.5.5 EXTRA_PARAMS='${EXTRA_PARAMS}'
	$(MAKE) build-rquadling-php-fpm-image PHP_VERSION=7.1 XDEBUG_VERSION=2.5.5 EXTRA_PARAMS='${EXTRA_PARAMS}'
	$(MAKE) build-rquadling-php-fpm-image PHP_VERSION=7.2 XDEBUG_VERSION=2.6.0 EXTRA_PARAMS='${EXTRA_PARAMS}'

build-rquadling-php-fpm-image:
	@echo Building rquadling/php-fpm:${PHP_VERSION}
	@echo ===============================
	@echo ""
	docker build ${EXTRA_PARAMS} --build-arg PHP_VERSION=${PHP_VERSION} --build-arg XDEBUG_VERSION=${XDEBUG_VERSION} -t rquadling/php-fpm:${PHP_VERSION} Sources/rquadling/php-fpm
	@echo ""
	@echo Completed rquadling/php-fpm:${PHP_VERSION}
	@echo ""
	@echo ""
```

and my docker-compose.yml
```yaml
version: '3'

networks:
  app-tier:
    driver: bridge

services:

  mysql:
    tty: true
    container_name: mysql
    image: 'bitnami/mysql:5.7.21-r1'
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      # Define the persistence layer for Bitnami's persistence container.
      - ./persistence:/bitnami
      # Mount the logs.
      - ./logs/mysql:/opt/bitnami/mysql/logs
    networks:
      - app-tier
    restart: always

  nginx:
    tty: true
    container_name: nginx
    image: 'bitnami/nginx:1.12.2-r0'
    env_file:
      - .env
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - php
    volumes:
      # Define the persistence layer for Bitnami's persistence container.
      - ./persistence:/bitnami
      # Mount the logs.
      - ./logs/nginx:/opt/bitnami/nginx/logs
      # Mount the code
      - ../app:/var/www/app
      - ../dtapps:/var/www/dtapps
      - ../data/phpmaker:/var/www/phpmaker
      - ../epos:/var/www/epos
    networks:
      - app-tier
    restart: always

  php:
    tty: true
    container_name: php
    image: 'rquadling/php-fpm:7.1'
    env_file:
      - .env
    ports:
      - '9000:9000'
    depends_on:
      - mailcatcher
      - memcached
      - redis
      - mysql
    volumes:
      # Define the persistence layer for Bitnami's persistence container.
      - ./persistence:/bitnami
      # Mount the logs.
      - ./logs/php:/opt/bitnami/php/logs
      # Mount the code
      - ../app:/var/www/app
      - ../dtapps:/var/www/dtapps
      - ../data/phpmaker:/var/www/phpmaker
      - ../epos:/var/www/epos
    networks:
      - app-tier
    restart: always

  memcached:
    tty: true
    container_name: memcached
    image: 'bitnami/memcached:1.5.4-r1'
    env_file:
      - .env
    ports:
      - '11211:11211'
    volumes:
      # Define the persistence layer for Bitnami's persistence container.
      - ./persistence:/bitnami
      # Mount the logs.
      - ./logs/memcached:/opt/bitnami/memcached/logs
    restart: always

  redis:
    tty: true
    container_name: redis
    image: 'bitnami/redis:4.0.8-r0'
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      # Define the persistence layer for Bitnami's persistence container.
      - ./persistence:/bitnami
      # Mount the logs.
      - ./logs/redis:/opt/bitnami/redis/logs
    restart: always

  mailcatcher:
    tty: true
    container_name: mailcatcher
    image: mailhog/mailhog
    env_file:
      - .env
    ports:
      - '1025:1025'
      - '1080:8025'
    volumes:
      - ./persistence/email:/home/mailhog/email
    command: -maildir-path /home/mailhog/email -storage maildir
    restart: always
```
