### ISSUE TITLE
php not being displayed when using bitnami nginx and php-fpm containers

### ISSUE THREAD

**Issue by HeadBanging** [bitnami/bitnami-docker-php-fpm#102]
**Description**

Unable to get bitnami nginx container (bitnami/nginx:latest) to work with bitnami php-fpm container (bitnami/php-fpm:latest).  HTML pages load correctly - PHP doesn't load, resulting in a plain (not 404) 'file not found' and error in logs 'FastCGI send in stderr "Primary Script Unknown" while reading response header from upstream' 

**Steps to reproduce the issue:**

1. Create yml file for docker compose containing the following:
```
version: '2'

networks:
  app-tier:
    driver: bridge

services:
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
        - phpfpm
    networks:
        - app-tier
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./nginx/nginx.conf:/bitnami/nginx/conf/nginx.conf
      - ./nginx/fastcgi.conf:/bitnami/nginx/conf/fastcgi.conf
      - ./logs:/opt/bitnami/nginx/logs
      - ./nginx/vhosts:/bitnami/nginx/conf/vhosts
      - ./public:/opt/bitnami/nginx/html
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
      - ./public:/app
      - ./logs/php:/opt/bitnami/php/log
      - ./php/php.ini:/opt/bitnami/php/etc/php.ini
      - ./php/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
    working_dir: /app
```
2. Create directories as described above (.logs, .nginx, etc)
3. Copy default config files from container into local location to provide base point to edit from
4. Create simple index.html file and simple info.php file
5. Create vhost file for website
```
server {
        listen 0.0.0.0:8080;
        server_name  www.my_website_example.com;
        server_tokens off;
 
        error_log "/opt/bitnami/nginx/logs/my_website_example-error.log";
        access_log  "/opt/bitnami/nginx/logs/my_website_example-access.log";
        root   /opt/bitnami/nginx/html/my_website_example/htdocs; 

        location / {
                try_files $uri $uri/index.php;
        }

        location ~ \.php$ {
         # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
                fastcgi_pass phpfpm:9000;
                fastcgi_index index.php;
                include fastcgi.conf;
         }
 
        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
        }
}
```
6. Start containers
docker-compose up --remove-orphans -d

**Describe the results you received:**

Docker Compose returns no errors.
Visiting html page at website returns no errors and displays correctly.
Visiting php page at website results in a plain (not 404) 'file not found' and error in logs 'FastCGI send in stderr "Primary Script Unknown" while reading response header from upstream'
This suggests to me that the php page is seen and loaded by nginx (hence not a 404) but the php-fpm cannot be connected to to display the php content.

**Describe the results you expected:**

I expected phpinfo to be displayed.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is reproducible every time.  Right now this is a simple config, built using bitnami instructions - I want to get php-fpm working before I try adding in the bitnami mariadb container.

**Version**

- Output of `docker version`:

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 19
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-109-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.8 MiB
Name: Aitherios
ID: TVRZ:OIN2:PHUQ:OZOC:XA7D:CMJM:POLM:YN36:3J6G:TQLN:6R3O:HB3W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.7.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by HeadBanging** [comment]
Okay - I get that.  Presumably I could also change the working dir in the docker compose yml file to achieve the same end - just one problem.  If I then add another vhost (as I intend to), how can I have this php configuration serve both of them?
The app root will need to be unique for each website, and accessed according to its server_name.

**Comment by javsalgar** [comment]
Hi,

There is something I did not understand correctly. Wouldn't simply adding another server block with `root` to the path you are looking for and setting a different `server_name` work for your case?

**Comment by HeadBanging** [comment]
Hi Javsalgar - under those circumstances both site1.com and site2.com would be looking for their files under root, so they'd both show the same content.

**Comment by javsalgar** [comment]
Hi,

If, in the second server block you change the `root` parameter to another location, that shouldn't happen. Am I missing something?

**Comment by HeadBanging** [comment]
Hi Javsalgar - that sounds great.  How?  Please could you provide instructions so that I can try it out?

**Comment by HeadBanging** [comment]
Looking at this site (https://www.digitalocean.com/community/tutorials/how-to-host-multiple-websites-securely-with-nginx-and-php-fpm-on-ubuntu-14-04) it looks to me as if PHP requires pools to be configured to support multiple vhosts (server names).  Can this be done with the bitnami php-fpm docker container?

**Comment by javsalgar** [comment]
Hi,

I was able to have two virtual hosts. Just as you said, what I did is to have two php-fpm instances, one per app. This is the configuration I used:

docker-compose.yml
```
version: '2'

networks:
  app-tier:
    driver: bridge
services:
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
      - ./app1:/app
  phpfpm2:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
      - ./app2:/app
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
      - phpfpm2
    networks:
      - app-tier
    ports:
      - '8080:8080'
      - '443:443'
    volumes:
      - ./vhost.conf:/bitnami/nginx/conf/vhosts/yourapp.conf
```

vhost.conf
```
server {
  listen 0.0.0.0:8080;
  server_name myapp.com;

  root /app;

  location / {
    try_files $uri $uri/index.php;
  }

  location ~ \.php$ {
    # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
    fastcgi_pass phpfpm:9000;
    fastcgi_index index.php;
    include fastcgi.conf;
  }
}

server {
  listen 0.0.0.0:8080;
  server_name myapp2.com;

  root /app;

  location / {
    try_files $uri $uri/index.php;
  }

  location ~ \.php$ {
    # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
    fastcgi_pass phpfpm2:9000;
    fastcgi_index index.php;
    include fastcgi.conf;
  }
}
```
