### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by SysEngDan** [bitnami/bitnami-docker-php-fpm#138]
I'm having nothing but difficulty getting the site to (1) render properly and (2) save files properly.

**Question 1:** What is the correct user/UID & group/GID which the files should be owned on the local file system (meaning outside of any container, located on the docker host)?
**Question 2:** What should be the file and folder permissions which the files should be set on the local file system?

My experience has been that I have to chmod all files to 777 for the site to render (Wordpress website). Then I installed a backup plugin, created a backup, and upon downloading the static file, I get a "Permission Denied".

Docker 19.03.12
CentOS 7.6
Nginx: nginx:1.19.1
PHP-FPM: bitnami:7.4.9-prod
Source files: /san/data1/services/mywebsite.com/root/html
Deploy step: `docker stack deploy mywebsite_com -c /san/data1/services/mywebsite.com/docker-compose.yml`

**PHP-FPM Docker Compose**
```
version: '3'
services:
  php:
    image: bitnami/php-fpm:7.4.9-prod
    volumes:
      - /san/data1/services/mywebsite.com/root/html:/app
    extra_hosts:
      - "mywebsite.com:192.168.30.50"
      - "www.mywebsite.com:192.168.30.50"
    networks:
      - webproxy-overlay
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2048M
networks:
  webproxy-overlay:
    external: true
```

**Nginx Docker Compose**
```
version: '3.5'
services:
  frontend:
    image: nginx:1.19.1
    volumes:
      - /var/log/docker-nginx:/var/log/nginx
      - ./nginx:/etc/nginx
      - /san:/san
    ports:
      - "80:80"
      - "443:443"
      - "5020:5020"
    networks: 
      - webproxy-overlay
    deploy:
      restart_policy:
        condition: any
      replicas: 1
networks:
  webproxy-overlay:
    external: true
```

**Nginx Config for mywebsite.com**
```
server {
        listen 80;
        server_name mywebsite.com www.mywebsite.com;

        location ^~ /.well-known/acme-challenge/ {
                allow all;
                default_type "text/plain";
                root /etc/nginx/certs/letsencrypt/temp_auth;
        }

        location / {
            return 301 https://$server_name$request_uri;
        }
}
server {
        listen 443 ssl http2;
        server_name mywebsite.com www.mywebsite.com;
        ssl_certificate /etc/nginx/certs/letsencrypt/live/mywebsite.com/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/letsencrypt/live/mywebsite.com/privkey.pem;
        add_header Strict-Transport-Security "max-age=31536000";
        ssl_session_cache shared:SSL:20m;
        ssl_session_timeout 10m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';

        root /san/data1/services/mywebsite.com/root/html;

        location / {
                real_ip_header proxy_protocol;
                set_real_ip_from 192.168.30.1/32;
                try_files $uri $uri/index.php;
        }

        location ~ \.php$ { 
                resolver 127.0.0.11 valid=10s;
                real_ip_header proxy_protocol;
                set_real_ip_from 192.168.30.1/32;
                set $upstream mywebsite_com_php;
                fastcgi_pass $upstream:9000;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
        }
}
```
