### ISSUE TITLE
php-fpm + nginx: File not found

### ISSUE THREAD

**Issue by neoacevedo** [bitnami/bitnami-docker-php-fpm#147]
**Description**

**Steps to reproduce the issue:**

1. docker pull bitnami/php-fpm and bitnami/nginx
2. configured my docker compose file as explained in https://hub.docker.com/r/bitnami/php-fpm in the section _**Serving your PHP app through an nginx frontend**_
3. run the docker compose

**Describe the results you received:**

I assumed it was related to #102 but actually  when I try to access to any PHP I get the error **_File not found_** but I'm able to access to any other files. 

To get the PHP files working as expected.

**latest**

- Output of `docker version`:
```
localhost:~ # docker version
Client:
 Version:           20.10.6-ce
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        8728dd246c3a
 Built:             Thu Apr 15 00:00:00 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6-ce
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd246c3a
  Built:            Thu Apr 15 00:00:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0
  GitCommit:
 docker-init:
  Version:          0.1.5_catatonit
  GitCommit: 
```
</details>

- Output of `docker info`:
```
docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 10
  Running: 3
  Paused: 0
  Stopped: 7
 Images: 17
 Server Version: 20.10.6-ce
 Storage Driver: btrfs
  Build Version: Btrfs v5.12.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux oci
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.0-1-default
 Operating System: openSUSE Tumbleweed
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.724GiB
 Name: localhost.localdomain
 ID: 7WN2:RTGQ:7YSU:SYAZ:KQYZ:IJV4:V266:UVOW:S5GS:S7RT:OTIS:6DR2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```
- Output of `docker-compose version` (if applicable):

```
localhost:~ # docker-compose version
docker-compose version 1.28.5, build unknown
docker-py version: 4.4.4
CPython version: 3.6.13
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
physical. openSUSE Tumbleweed 20210711

**Comment by alvneiayu** [comment]
hi @neoacevedo 

Could you share your docker-compose, please? To try reproduce the problem.

Thanks a lot

Álvaro

**Comment by neoacevedo** [comment]
```yaml
version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    command: '--transaction-isolation=READ-COMMITTED --binlog-format=ROW'
    volumes:
      - '/var/lib/mysql:/var/lib/mysql'
    environment:
      - TZ=America/Bogota
    ports:
      - '3307:3306'
    networks:
      app:
        ipv4_address: 172.20.0.3
  php-apache:
    image: 'webdevops/php-apache:7.4'
    restart: always
    depends_on:
      - db
    environment:
      - TZ=America/Bogota
    volumes:
      - '/app:/app'
    ports:
      - '8080:80'
    networks:
      app:
        ipv4_address: 172.20.0.2
networks:
  app:
    ipam:
      config:
        - subnet: 172.20.0.0/24

```
