### ISSUE TITLE
Latest releases do not initialize the configuration files anymore

### ISSUE THREAD

**Issue by juban** [bitnami/bitnami-docker-php-fpm#99]
As of latest released images for 5.6, 7.0, 7.1 and 7.2, mounting the /bitnami to a local folder do not initialize the configuration files as described in the 'Configuration' section of the README. 
The mounted folder remain empty and the configurations files are ignored from the container.

**Comment by chipironcin** [comment]
In a recent change we removed installation logic as it is no longer needed.
In that removal, the symlink from several php-fpm useful directories to `/bitnami` was also gone.

Documentation is wrong and outdated.

Please use this docker-compose while we tackle this issue:
```
version: '2'

services:
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    ports:
      - '9000:9000'
    volumes:
      - /path/to/php-fpm-conf:/opt/bitnami/php-fpm/etc
```

Thanks for reporting it 👍
